baseURL = "https://www.jobdoneright.co.uk/"
languageCode = "en-us"
title = "Job Done Right"
theme = "minimal"

[taxonomies]
  category = "categories"
  tag = "tags"

[params]
    accent = "blue"
    showBorder = true
    backgroundColor = "white"
    description = "Open Source Cloud Consultancy"
    githubUsername = "#"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 2

[[menu.main]]
    url = "/posts/"
    name = "Posts"
    weight = 3

[[menu.main]]
    url = "/projects/"
    name = "Projects"
    weight = 4

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "mailto:simon@jobdoneright.co.uk"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/jobdoneright/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/jobdoneright/"
    name = "twitter"
    weight = 3
